### ISSUE TITLE
Not able to see code snippets from within .cljc files

### ISSUE THREAD

**Issue by petterik** [magnars/prone#33]
I cannot see code snippets from `.cljc` files.

Did: 
* threw an exception from a `.cljc` file

Happened:
* The prone exception UI was shown in my browser, but there were issues with the frame to the right which shows code snippets.
  * Instead of showing code, it was grey and had a label: `(could not locate source file on class path)`
  * The top left label showing the path to the file was: "com/company/file.java", expected file extension to be `.cljc` not `.java`.
  * The top right label showing the function name, seems to always say `invoke` or `doInvoke` for `.cljc` files.

I don't have any problems with `.clj` files.
I have not tried to reproduce this with a minimal setup yet. Will update this issue when I have.

**Comment by magnars** [comment]
Thanks for the report. I see lots of `(.endsWith ".clj")` and stuff like that in the source, so there's no need to add a minimal setup.

**Comment by magnars** [comment]
Am I doing this wrong somehow?

```
prone git:(master) lein with-profile 1.7 test
Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil, compiling:(prone/middleware.clj:43:1)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.RT.loadResourceScript(RT.java:371)
	at clojure.lang.RT.loadResourceScript(RT.java:362)
	at clojure.lang.RT.load(RT.java:446)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at prone.middleware_test$eval359$loading__5340__auto____360.invoke(middleware_test.clj:1)
	at prone.middleware_test$eval359.invoke(middleware_test.clj:1)
        ...
```
