### ISSUE TITLE
Prone throws an IndexOutOfBoundsException handling a org.postgresql.util.PSQLException

### ISSUE THREAD

**Issue by codahale** [magnars/prone#38]
My application throws an exception like this:

```clojure
#error {
 :cause "Can't infer the SQL type to use for an instance of clojure.lang.Keyword. Use setObject() with an explicit Types value to specify the type to use."
 :via
 [{:type org.postgresql.util.PSQLException
   :message "Can't infer the SQL type to use for an instance of clojure.lang.Keyword. Use setObject() with an explicit Types value to specify the type to use."
   :at [org.postgresql.jdbc.PgPreparedStatement setObject "PgPreparedStatement.java" 1039]}]
 :trace
 [[org.postgresql.jdbc.PgPreparedStatement setObject "PgPreparedStatement.java" 1039]
  [com.zaxxer.hikari.pool.HikariProxyPreparedStatement setObject "HikariProxyPreparedStatement.java" -1]
  [clojure.java.jdbc$eval4067$fn__4068 invokePrim "jdbc.clj" 341]
;;; etc
```

But instead of Prone’s lovely debug UI, I get this:

```
java.lang.IndexOutOfBoundsException
	at clojure.lang.PersistentVector.arrayFor(PersistentVector.java:158)
	at clojure.lang.PersistentVector.nth(PersistentVector.java:162)
	at clojure.lang.RT.nth(RT.java:853)
	at prone.code_trunc$find_top_level_form.invokeStatic(code_trunc.clj:18)
	at prone.code_trunc$find_top_level_form.invoke(code_trunc.clj:8)
	at prone.code_trunc$truncate.invokeStatic(code_trunc.clj:54)
	at prone.code_trunc$truncate.invoke(code_trunc.clj:38)
	at prone.prep$load_source.invokeStatic(prep.clj:26)
	at prone.prep$load_source.invoke(prep.clj:20)
	at prone.prep$add_source.invokeStatic(prep.clj:30)
	at prone.prep$add_source.invoke(prep.clj:29)
	at clojure.core$mapv$fn__6953.invoke(core.clj:6627)
	at clojure.core.protocols$fn__6755.invokeStatic(protocols.clj:167)
	at clojure.core.protocols$fn__6755.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__6710$G__6705__6719.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6545)
	at clojure.core$mapv.invokeStatic(core.clj:6618)
	at clojure.core$mapv.invoke(core.clj:6618)
	at prone.prep$prep_error$fn__12840.invoke(prep.clj:114)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$update_in.invokeStatic(core.clj:5950)
	at clojure.core$update_in.doInvoke(core.clj:5939)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at prone.prep$prep_error.invokeStatic(prep.clj:110)
	at prone.prep$prep_error.invoke(prep.clj:106)
	at prone.prep$prep_error_page.invokeStatic(prep.clj:149)
	at prone.prep$prep_error_page.invoke(prep.clj:148)
	at prone.middleware$exceptions_response.invokeStatic(middleware.clj:92)
	at prone.middleware$exceptions_response.invoke(middleware.clj:87)
	at prone.middleware$wrap_exceptions$fn__12928.invoke(middleware.clj:129)
(etc)
```

This is using HugSQL, FWIW, so some of the functions the exception passes through are created by macros.

**Comment by magnars** [comment]
Thanks for the report. I'll take a look.

**Comment by magnars** [comment]
It seems like you have a line number that is higher than the number of lines in the file. So that is slightly weird. Do you have a chance to figure out which file is the culprit and how that could have happened?

If we can't figure out the actual cause, I can add some guard against this exception and just bail out on showing the code if we get this weird edge case.

**Comment by codahale** [comment]
I suspect it’s something to do with HugSQL? I don’t know. It only happens with errors from the database — Prone works wonderfully for everything else.

**Comment by magnars** [comment]
Any chance you could tear out everything else and make a minimal project
that I could use to reproduce it?
tir. 29. mar. 2016 kl. 21.39 skrev Coda Hale <notifications@github.com>:

**Comment by codahale** [comment]
I’ll certainly see if I can, but I don’t think I’ll be able to get around to it soon.

---
Coda Hale
http://codahale.com

**Comment by magnars** [comment]
I have a rare case of some free time this weekend, so for an expedient fix
that would be helpful before then. I don't use hugSQL myself, so it'd take
quite some time just to get everything up. Fully understand if that's hard
to fit in tho. Thanks for the report regardless. :)
tir. 29. mar. 2016 kl. 21.49 skrev Coda Hale <notifications@github.com>:

**Comment by csummers** [comment]
Author of HugSQL here...I was curious if HugSQL was triggering this, so I created a repo reproducing the  error @codahale is seeing.  Turns out, I was able to reproduce this without HugSQL.

See here: https://github.com/csummers/prone-issue-38

**Comment by codahale** [comment]
That’s awesome, @csummers. Thanks for the repro — and for HugSQL!

**Comment by magnars** [comment]
Outstanding. Thanks, Curtis. :)

**Comment by magnars** [comment]
Hey, check out this frame:

```
                  jdbc.clj:   -1  clojure.java.jdbc/eval19552/fn
```

That's an outlier if I ever saw one.

**Comment by magnars** [comment]
`1.1.1` released with this fix.

**Comment by csummers** [comment]
Happy to help.  Thanks for prone. It's a beautiful tool.
